sudo: false
language: python
cache: pip
python:
    - "2.7"
    - "3.5"
addons:
    postgresql: "9.4"
services:
    - postgresql
branches:
    only:
        - master
        - parkstay
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
        - PRODUCTION_EMAIL=False
        - EMAIL_INSTANCE="TEST"
        - NON_PROD_EMAIL="travis@dpaw.wa.gov.au"
        - BPAY_ALLOWED=False
sudo: true
install:
    - sudo apt-get install postgresql-9.4-postgis-2.3 postgis -y -q
    - pip install pip --upgrade
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage_wl.py migrate --noinput
    - python manage_ps.py migrate --noinput
script:
    - coverage run --source="." manage_wl.py test
after_success:
    - coveralls
