sudo: false
language: python
cache: pip
python:
    - "2.7"
    - "3.5"
addons:
    postgresql: "9.4"
services:
    - postgresql
branches:
    only:
        - master
env:
    global:
        - SECRET_KEY=SecretKeyForTravis
        - DATABASE_URL="postgis://postgres@localhost:5432/travis_ci_test"
install:
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
    - python manage_wl.py migrate --noinput
    - python manage_ps.py migrate --noinput
script:
    - coverage run --source="." manage_wl.py test
after_success:
    - coveralls
